[
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 10,
        "title": "real robot deployment ",
        "body": "PaddleRobotics/QuadrupedalRobots/ETGRL/\r\n\r\nstep3：Real Robot Deployment\r\n\r\nquestion1:An error occurs when running env_test.py.\r\nTypeErro:step() got an unexpected keyword argument 'donef'\r\n\r\nquestion2: An error occurs when running test.py.\r\nModuleNotFoundError:No module named'model.sac'",
        "state": "open",
        "user": "Tang0707",
        "closed_by": null,
        "created_at": "2021-11-16T08:59:31+00:00",
        "updated_at": "2021-11-16T08:59:31+00:00",
        "closed_at": null,
        "comments_count": [],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 12,
        "title": "实际部署的npy和pt文件",
        "body": "Hi, 你好，请问你们可以提供你们实际部署到真狗里面的6种场景的npy和pt文件吗，参考论文https://arxiv.org/abs/2109.06409，谢谢！",
        "state": "open",
        "user": "JeffXu1",
        "closed_by": null,
        "created_at": "2022-01-25T01:54:30+00:00",
        "updated_at": "2022-01-25T01:54:30+00:00",
        "closed_at": null,
        "comments_count": [],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 3,
        "title": "期待一下",
        "body": "",
        "state": "closed",
        "user": "universea",
        "closed_by": "lijiangyong01",
        "created_at": "2020-12-23T03:00:31+00:00",
        "updated_at": "2020-12-23T08:10:48+00:00",
        "closed_at": "2020-12-23T08:10:48+00:00",
        "comments_count": [],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 13,
        "title": "运行 python train.py --task_mode stairstair --ETG_path data/origin_ETG/ESStair_origin.npz报错",
        "body": "pybullet build time: Feb 10 2022 08:59:07\r\nC:\\Users\\zhaojiu\\anaconda3\\lib\\site-packages\\rlschool\\quadrupedal\\robots\\a1.py:92: RuntimeWarning: invalid value encountered in arccos\r\n  theta_knee = -np.arccos(\r\n[03-23 17:42:13 MainThread @logger.py:242] Argv: train.py --task_mode stairstair --ETG_path data/origin_ETG/ESStair_origin.npz\r\ncuda\r\nETG_param_init: (12,)\r\n{'dis': 1, 'motor': 1, 'imu': 1, 'contact': 1, 'footpose': 0, 'ETG': 1, 'ETG_obs': 0, 'dynamic_vec': 0, 'force_vec': 0, 'noise': 0, 'RNN': {'time_steps': 5, 'time_interval': 1, 'mode': 'None'}}\r\nargv[0]=\r\nstarting thread 0\r\nstarted testThreads thread 0 with threadHandle 0000000000000EF0\r\nargc=3\r\nargv[0] = --unused\r\nargv[1] =\r\nargv[2] = --start_demo_name=Physics Server\r\nExampleBrowserThreadFunc started\r\nVersion = 4.6.0 NVIDIA 472.19\r\nVendor = NVIDIA Corporation\r\nRenderer = NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2\r\nb3Printf: Selected demo: Physics Server\r\nstarting thread 0\r\nstarted MotionThreads thread 0 with threadHandle 000000000000109C\r\nMotionThreadFunc thread started\r\nc:\\users\\zhaojiu\\gym\\gym\\spaces\\box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32\r\n  logger.warn(f\"Box bound precision lowered by casting to {self.dtype}\")\r\nC:\\Users\\zhaojiu\\anaconda3\\lib\\site-packages\\rlschool\\quadrupedal\\robots\\minitaur.py:188: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated si\r\nnce Python 3.3, and in 3.9 it will stop working\r\n  if isinstance(motor_kp, (collections.Sequence, np.ndarray)):\r\nobs_dim: 49\r\nTraceback (most recent call last):\r\n  File \"train.py\", line 523, in <module>\r\n    main()\r\n  File \"train.py\", line 452, in main\r\n    ETG_info = np.load(args.load[:-3] + \".npz\")\r\n  File \"C:\\Users\\zhaojiu\\anaconda3\\lib\\site-packages\\numpy\\lib\\npyio.py\", line 407, in load\r\n    fid = stack.enter_context(open(os_fspath(file), \"rb\"))\r\nFileNotFoundError: [Errno 2] No such file or directory: '.npz'\r\nnumActiveThreads = 0\r\nstopping threads\r\nThread with taskId 0 with handle 000000000000109C exiting\r\nThread TERMINATED\r\nfinished\r\nnumActiveThreads = 0\r\nbtShutDownExampleBrowser stopping threads\r\nThread with taskId 0 with handle 0000000000000EF0 exiting\r\nThread TERMINATED\r\n",
        "state": "open",
        "user": "zhaojiu97",
        "closed_by": null,
        "created_at": "2022-03-23T09:51:58+00:00",
        "updated_at": "2023-11-20T11:52:48+00:00",
        "closed_at": null,
        "comments_count": [
            "zhaojiu97",
            "KiriyamaGK",
            "bld2013"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 5,
        "title": "要是TFVT_HRI的模型可以公开就好了",
        "body": "开发环境搭建倒是不难，难的就是数据的收集，长达数小时的视频数据收集，还有标注，这个工作量实在是大",
        "state": "open",
        "user": "MiChongGET",
        "closed_by": null,
        "created_at": "2021-03-16T13:28:11+00:00",
        "updated_at": "2021-11-15T08:24:54+00:00",
        "closed_at": null,
        "comments_count": [
            "WorldEditors"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 4,
        "title": "请问TFVT_HRI的模型可以公布吗",
        "body": "代码中 MobileNetV2_Pretrained = 'pretrain_models/MobileNetV2_pretrained' 的模型可以提供吗",
        "state": "closed",
        "user": "leelinglin",
        "closed_by": "xueeinstein",
        "created_at": "2020-12-28T07:01:47+00:00",
        "updated_at": "2020-12-29T08:57:05+00:00",
        "closed_at": "2020-12-29T02:19:47+00:00",
        "comments_count": [
            "xueeinstein",
            "leelinglin"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 8,
        "title": "Evaluation in simulation报错",
        "body": "使用python train.py命令评估模型时报如下错误\r\npython train.py --task_mode stairstair --eval 1 --load data/model/StairStair_3_itr_960231.pt\r\n[10-20 10:50:54 MainThread @logger.py:242] Argv: train.py --task_mode stairstair --eval 1 --load data/model/StairStair_3_itr_960231.pt\r\npybullet build time: Oct 11 2021 20:59:00\r\n/home/xh/PycharmProjects/pythonProject2/venv/lib/python3.7/site-packages/rlschool-1.0.2-py3.7.egg/rlschool/quadrupedal/robots/a1.py:94: RuntimeWarning: invalid value encountered in arccos\r\n  (2 * l_low * l_up))\r\nTraceback (most recent call last):\r\n  File \"train.py\", line 508, in <module>\r\n    main()\r\n  File \"train.py\", line 309, in main\r\n    enable_action_filter=args.enable_action_filter)\r\n  File \"/home/xh/PycharmProjects/pythonProject2/venv/lib/python3.7/site-packages/rlschool-1.0.2-py3.7.egg/rlschool/__init__.py\", line 17, in make_env\r\n    raise Exception(\"rlschool.make_env is deprecated. Please do \\\"import rlschool.xxxenv\\\" and use gym.make instead\")\r\nException: rlschool.make_env is deprecated. Please do \"import rlschool.xxxenv\" and use gym.make instead",
        "state": "open",
        "user": "JeffXu1",
        "closed_by": null,
        "created_at": "2021-10-20T05:53:25+00:00",
        "updated_at": "2021-11-15T08:01:36+00:00",
        "closed_at": null,
        "comments_count": [
            "WorldEditors"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 11,
        "title": "运行train.py报错  'MujocoModel' object has no attribute 'to'",
        "body": "使用python train.py时报如下错误\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py\", line 508, in <module>\r\n    main()\r\n  File \"/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py\", line 331, in main\r\n    critic_lr=CRITIC_LR)\r\n  File \"/home/ros/PaddleRobotics\\QuadrupedalRobots\\ETGRL\\alg\\sac.py\", line 53, in __init__\r\n    self.model = model.to(device)\r\nAttributeError: 'MujocoModel' object has no attribute 'to'",
        "state": "open",
        "user": "Hgy-ang",
        "closed_by": null,
        "created_at": "2021-12-10T09:55:08+00:00",
        "updated_at": "2023-02-17T07:13:49+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013",
            "woderrrrr"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 7,
        "title": "ETGRL/deployment/test.py库文件robot_interface找不到",
        "body": "在使用提供代码里面的PaddleRobotics/QuadrupedalRobots/ETGRL/deployment/test.py测试时，提示需要安装robot_interface库，这个库在PaddleRobotics/QuadrupedalRobots/ETGRL/deployment/robots/a1_robot.py中被调用，但是我在网络上没有搜索到对应的开源库，请问您那边提供这个库的下载地址吗？",
        "state": "open",
        "user": "JeffXu1",
        "closed_by": null,
        "created_at": "2021-10-19T08:22:54+00:00",
        "updated_at": "2022-02-12T12:49:09+00:00",
        "closed_at": null,
        "comments_count": [
            "zzzbbs",
            "JeffXu1",
            "zzzbbs"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 14,
        "title": "Dynamic_train时加载data/dynamic/内的数据含义请教",
        "body": "作者您好，我在研读了你们发表的论文后想跑一下这个项目，但是在看域自适应训练代码时遇到一些模糊的地方，想请教一下。\r\n\r\n在运行Dynamic_train.py时，下面这行代码：\r\n`MEAN_INFO = np.load(\"data/dynamic/mean_dict_5_18.npz\")`   # data used for dynamic adaptation\r\n加载进来的数据的键分别代表什么意思呢？\r\ndict_keys(['exp_motor_mean', 'exp_motor_std', 'exp_drpy_mean', 'exp_drpy_std', 'ori_motor_mean', 'ori_motor_std', 'ori_drpy_mean', 'ori_drpy_std', 'height_motor_mean', 'height_motor_std', 'height_drpy_mean', 'height_drpy_std'])\r\n\r\n下面代码：\r\n```\r\nGAIT_LIST[\"exp\"] = np.load(\"data/dynamic/gait_action_list_t0.3.npy\")\r\nGAIT_LIST[\"ori\"] = np.load(\"data/dynamic/gait_action_list_CPG_ori.npy\")\r\nGAIT_LIST[\"height\"] = np.load(\"data/dynamic/gait_action_list_CPG_height.npy\")\r\n```\r\n加载进来的是什么数据呢？不知道您是否方便公开一下，谢谢\r\n\r\n@xueeinstein ",
        "state": "open",
        "user": "Senwei-Huang",
        "closed_by": null,
        "created_at": "2022-04-23T14:45:25+00:00",
        "updated_at": "2022-04-27T13:19:36+00:00",
        "closed_at": null,
        "comments_count": [
            "xueeinstein",
            "TomorrowIsAnOtherDay",
            "Senwei-Huang",
            "TomorrowIsAnOtherDay",
            "Senwei-Huang",
            "TomorrowIsAnOtherDay",
            "Senwei-Huang"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 19,
        "title": "模型替换问题",
        "body": "您好，想问以下几个问题：\r\n1、论文中用到的四足机器人可以替换吗？比如说我们自己利用三维建模软件建了一个多足机器人，可以替换到这个论文里吗？\r\n2、这个论文中用到的ETG的方法是和RL并行运算的吗？是不是运行train就可以进行训练了？",
        "state": "open",
        "user": "wzj-651123",
        "closed_by": null,
        "created_at": "2022-08-10T07:03:37+00:00",
        "updated_at": "2022-08-10T07:03:37+00:00",
        "closed_at": null,
        "comments_count": [],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 16,
        "title": "ValueError: device value error, must be str,",
        "body": "请问一下，我只在仿真环境中跑了train.py, 按照readme的指导，但是报告了一个异常，\r\nValueError: device value error, must be str, paddle.CPUPlace(), paddle.CUDAPlace(), paddle.CUDAPinnedPlace() or paddle.XPUPlace(), but the type of device is device\r\n我测试了一下，device=cuda,  type(decvice) = <class 'torch.device'>, 一直找不到哪里的问题,可以帮忙看一下么？",
        "state": "open",
        "user": "IverYangg",
        "closed_by": null,
        "created_at": "2022-06-13T06:41:12+00:00",
        "updated_at": "2022-10-11T08:21:44+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013",
            "PIKACHU-BOOM",
            "bld2013",
            "IverYangg",
            "PIKACHU-BOOM",
            "bld2013"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 15,
        "title": "运行Dynamic_train.py时报错Exception in thread Thread-2：parl.remote.exceptions.RemoteError: [PARL remote error when calling function __init__]:",
        "body": "**作者您好，我运行QuadrupedalRobots/ETGRL/train.py训练是没有问题的，但是运行Dynamic_train.py时出现了下面3个问题，查看Dynamic_train.py同级目录里是有./model/Dynamic_parallel_model.py文件的，请问是什么原因造成的呢？**\r\n\r\nException in thread Thread-2:\r\nparl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:\r\n\r\n[Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\nFileNotFoundError: [Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\n\r\nparl.remote.exceptions.FutureFunctionError: There is an error raised when calling the future function `__init__`.\r\n\r\n\r\n## 完整报错信息\r\n[04-26 20:29:14 MainThread @Dynamic_train.py:71] args:Namespace(K=20, alg='ga', eval=0, gamma=1, load='', outdir='Dynamic', sigma=0.1, steps=10000, suffix='exp0', thread=2, xparl='192.168.30.145:8037')\r\nException in thread Thread-5:\r\nTraceback (most recent call last):\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\r\n    self.run()\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/threading.py\", line 870, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/future_mode/proxy_wrapper_nowait.py\", line 92, in _run_object_in_backend\r\n    raise e\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/future_mode/proxy_wrapper_nowait.py\", line 82, in _run_object_in_backend\r\n    self._xparl_remote_wrapper_obj = remote_wrapper(\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_wrapper.py\", line 107, in __init__\r\n    raise RemoteError('__init__', traceback_str)\r\nparl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:\r\n[Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\ntraceback:\r\nTraceback (most recent call last):\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/job.py\", line 297, in wait_for_connection\r\n    cls = load_remote_class(message[1])\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_class_serialization.py\", line 207, in load_remote_class\r\n    with open(file_name + '.py') as t_file:\r\nFileNotFoundError: [Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\n\r\nException in thread Thread-4:\r\nTraceback (most recent call last):\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\r\n    self.run()\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/threading.py\", line 870, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/future_mode/proxy_wrapper_nowait.py\", line 92, in _run_object_in_backend\r\n    raise e\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/future_mode/proxy_wrapper_nowait.py\", line 82, in _run_object_in_backend\r\n    self._xparl_remote_wrapper_obj = remote_wrapper(\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_wrapper.py\", line 107, in __init__\r\n    raise RemoteError('__init__', traceback_str)\r\nparl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:\r\n[Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\ntraceback:\r\nTraceback (most recent call last):\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/job.py\", line 297, in wait_for_connection\r\n    cls = load_remote_class(message[1])\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_class_serialization.py\", line 207, in load_remote_class\r\n    with open(file_name + '.py') as t_file:\r\nFileNotFoundError: [Errno 2] No such file or directory: './model/Dynamic_parallel_model.py'\r\n\r\nTraceback (most recent call last):\r\n  File \"/mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/Dynamic_train.py\", line 74, in <module>\r\n    main()\r\n  File \"/mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/Dynamic_train.py\", line 72, in main\r\n    model.train(args.steps)\r\n  File \"/mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/model/Dynamic_parallel_model.py\", line 159, in train\r\n    mean_re = self.update(epoch) \r\n  File \"/mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/model/Dynamic_parallel_model.py\", line 128, in update\r\n    future_objects.append(self.agent_list[i].batch_sample_episodes(param=solutions[i*self.K:(i+1)*self.K,:],K = self.K))\r\n  File \"/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/future_mode/proxy_wrapper_nowait.py\", line 144, in __getattr__\r\n    raise self._xparl_remote_object_exception\r\nparl.remote.exceptions.FutureFunctionError: There is an error raised when calling the future function `__init__`.\r\nYou can see the detailed error message above, which is printed by another thread.\r\n\r\nProcess finished with exit code 1\r\n\r\n## 环境\r\nUbuntu 18.04\r\npython 3.8\r\nparl = 1.4.0\r\ntorch = 1.7.0\r\nrlschool = 1.0.2\r\n\r\n@xueeinstein ",
        "state": "open",
        "user": "Senwei-Huang",
        "closed_by": null,
        "created_at": "2022-04-27T01:57:50+00:00",
        "updated_at": "2022-04-28T03:17:59+00:00",
        "closed_at": null,
        "comments_count": [
            "Senwei-Huang",
            "TomorrowIsAnOtherDay",
            "Senwei-Huang",
            "TomorrowIsAnOtherDay",
            "Senwei-Huang"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 18,
        "title": "找不到robot_interface module",
        "body": "编译中报错找不到robot_interface module，请问怎样能解决此问题",
        "state": "open",
        "user": "timestube",
        "closed_by": null,
        "created_at": "2022-08-04T07:10:14+00:00",
        "updated_at": "2022-08-04T07:10:35+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 17,
        "title": "奖励函数的设置",
        "body": "你好，想请教一下奖励函数如何设置的问题。\r\n在文件Monitornv.py中，有这样的设置\r\n![reward function from code ](https://user-images.githubusercontent.com/63235229/180025577-4e9825ad-f1aa-4314-900a-2e0ae66e017f.png)\r\n不知道是否和论文中所阐述的奖励函数对应上了，论文中关于奖励函数的设置感觉比较简单，是否有更详细的说明?",
        "state": "open",
        "user": "IverYangg",
        "closed_by": null,
        "created_at": "2022-07-20T15:50:01+00:00",
        "updated_at": "2022-07-20T15:50:25+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 20,
        "title": "HRI/TFVT_HRI : No module named 'interaction.common.discrete_uc_ctrl",
        "body": "  File \"HRI/TFVT_HRI/interaction/action.py\", line 2, in <module>\r\n    from interaction.common.discrete_uc_ctrl import DiscreteUCController\r\nModuleNotFoundError: No module named 'interaction.common.discrete_uc_ctrl'\r\n\r\nThe common directory dont have the discrete_uc_ctrl.py :\r\ndata.py  data_via_decord.py  discrete_ctrl.py  __init__.py  __pycache__  utils.py\r\n\r\ncan you provide it?\r\n\r\nthanks",
        "state": "open",
        "user": "tarikbeijing",
        "closed_by": null,
        "created_at": "2022-10-31T00:56:58+00:00",
        "updated_at": "2022-10-31T00:57:18+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013"
        ],
        "labels": []
    },
    {
        "repo": "PaddlePaddle/PaddleRobotics",
        "number": 21,
        "title": "pretrain.py中缺失函数run_evaluate_epiosdes",
        "body": "pretrain.py第264行缺失函数run_evaluate_episodes的定义，能重新发一下这个文件吗？谢谢！",
        "state": "open",
        "user": "JianxiangL",
        "closed_by": null,
        "created_at": "2023-04-22T08:52:39+00:00",
        "updated_at": "2023-04-22T08:52:59+00:00",
        "closed_at": null,
        "comments_count": [
            "bld2013"
        ],
        "labels": []
    }
]